version: '1'
services:
  app:
    build: ./app/
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  db:
    image: postgres:latest
    build: ./db/
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    volumes:
      - ./db/init_scripts/init.sql:/docker-entrypoint/initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5
    restart: always
